### PR TITLE
Update to include CData Software Couchbase drivers

### PR DESCRIPTION
**Pull request by JerodJ**

### CODE REVIEW

**Comment by mattcarabine** [comment]
Thanks for the contribution @JerodJ - just verifying this change with our product management team and then will handle it.

**Comment by JerodJ** [comment]
Hi @mattcarabine, any update here?

**Comment by mattcarabine** [comment]
@JerodJ Just pinged product management again, should have an update soon.

**Comment by mattcarabine** [comment]
@cb-docs-robot backport to master

**Comment by mattcarabine** [comment]
@cb-docs-robot backport to 4.5

**Pull request merged**
