### PR TITLE
WIP -Fix DOC-1801 [For Review]

### PR DESCRIPTION
**Pull request by shilpalele**

### CODE REVIEW

**Comment by shilpalele** [comment]
@cb-docs-robot rebuild

**Comment by mattcarabine** [comment]
@cb-docs-robot rebuild

**Comment by mattcarabine** [comment]
@cb-docs-robot rebuild

**Comment by mattcarabine** [comment]
Not building due to problem with webhooks https://status.github.com/

**Comment by shilpalele** [comment]
@cb-docs-robot backport to 4.6

**Pull request merged**
