### PR TITLE
Update analytics docs for DP3

### PR DESCRIPTION
**Pull request by westmann**

### CODE REVIEW

**Comment by westmann** [comment]
@cb-docs-robot build analytics

**Comment by westmann** [comment]
@cb-docs-robot build analytics

**Comment by mattcarabine** [comment]
@cb-docs-robot build analytics

**Comment by westmann** [comment]
@cb-docs-robot build analytics

**Comment by mhubail** [comment]
@cb-docs-robot build analytics

**Comment by mhubail** [comment]
@cb-docs-robot build analytics

**Comment by mhubail** [comment]
@cb-docs-robot build analytics

**Pull request merged**
