### PR TITLE
Fix cbrestore date options

### PR DESCRIPTION
**Pull request by JFlath**

### CODE REVIEW

**Comment by JFlath** [comment]
@cb-docs-robot backport to 4.5

**Comment by JFlath** [comment]
@cb-docs-robot backport to 4.1

**Comment by JFlath** [comment]
@cb-docs-robot backport to 4.0

**Comment by mattcarabine** [comment]
Missed a spot.

**Comment by mattcarabine** [comment]
@cb-docs-robot backport to master

**Comment by JFlath** [comment]
5.0 isn't supported yet, why would I care about backporting to that ;)? Ta

**Pull request merged**
