### PR TITLE
Update sample-app-backend.dita

### PR DESCRIPTION
**Pull request by mnunberg**
Add mention of RBAC

### CODE REVIEW

**Comment by mattcarabine** [comment]
@mnunberg if you're not using Spock, do you need to specify a username and password to connect? I assumed the SDK would handle the legacy behaviour automatically.

In which case, probably doesn't make much sense for this to be put into 4.6, should probably just go into master (spock).

cc @ingenthr @1tylermitchell

**Comment by mnunberg** [comment]
Yes, this wouldn’t make much sense to place in 4.6 - the username/password stuff isn’t required in pre-spock.

**Comment by mattcarabine** [comment]
@cb-docs-robot backport to master

**Comment by 1tylermitchell** [comment]
5.0+ only please :)

**Pull request closed without merging**
