### PR TITLE
XTR-01: Added xattr shareable plus java overview and example

### PR DESCRIPTION
**Pull request by tonyjhillman**

### CODE REVIEW

**Comment by amarantha-k** [comment]
@1tylermitchell @ingenthr Since Tony is on vacation, wanted to check with you if these updates have been reviewed.

**Comment by ingenthr** [comment]
@amarantha-k I didn't get any requests to review this, no.  is that a request?

**Comment by 1tylermitchell** [comment]
@ingenthr It's not a bad idea to do a quick review, it's short content. There are only two pages really complete:
http://docs-build.sc.couchbase.com/server/1726/sdk/c/sdk-xattr-example.html
http://docs-build.sc.couchbase.com/server/1726/sdk/c/sdk-xattr-overview.html

@amarantha-k I think there should be some tweaks here - to having a non-language specific overview page instead of having overview under each language path - if you know what I mean.

**Pull request closed without merging**
