### PR TITLE
add style guide rules.

### PR DESCRIPTION
**Pull request by jamiltz**

### CODE REVIEW

**Comment by mattcarabine** [comment]
This is not really correct for dita. You should choose the correct semantic element, not a formatting element.

For example a file path should be '<filepath>' and a variable name should be '<varname>'.

**Comment by jamiltz** [comment]
Ok, then we should add the relevant tags in parenthesis as well. I'll update the PR with the tags that produce a bold font type and ones that produce an inline-code font type.

If a user writes `<bold>/Users/index.html</bold>` (assuming that the bold tag exists in Dita) instead of `<filepath>/Users/index.html</filepath>` the result should still be displayed as bold text.

**Comment by mattcarabine** [comment]
That is just down to the CSS, we should be using the correct semantic types and then get the web team to update the CSS so that we are consistent between server and mobile.

**Comment by jamiltz** [comment]
Yep agreed, I don't know what are all the tags that produce a bold font-face or a monospaced font-face. Any clues where I can find this info?

**Pull request closed without merging**
