### PR TITLE
Fix cbq CLI formatting

### PR DESCRIPTION
**Pull request by JFlath**

### CODE REVIEW

**Comment by JFlath** [comment]
@mattcarabine Not sure what you think about this change - I might be breaking some formatting rule...

**Comment by mattcarabine** [comment]
@cb-docs-robot backport to 4.5

**Comment by mattcarabine** [comment]
@cb-docs-robot backport to 4.6

**Comment by mattcarabine** [comment]
@cb-docs-robot backport to 4.1

**Comment by mattcarabine** [comment]
@cb-docs-robot backport to master

**Pull request merged**
