### PR TITLE
DOC-3628 - fix erroneous list of languages

### PR DESCRIPTION
**Pull request by 1tylermitchell**
Also, I added a note to mention more langs added in 5.5.
I didn't see a 5.1 branch to also apply this too.

### CODE REVIEW

**Comment by 1tylermitchell** [comment]
This needs to apply to 5.0 and 5.1.

**Comment by 1tylermitchell** [comment]
That's right Tony - thanks.

**Comment by amarantha-k** [comment]
@cb-docs-robot backport to 5.1

**Comment by amarantha-k** [comment]
@cb-docs-robot backport to 5.0.x

**Pull request merged**
