### PR TITLE
DOC-2083: Add missing VM recommendation

### PR DESCRIPTION
**Pull request by JFlath**

### CODE REVIEW

**Comment by JFlath** [comment]
@cb-docs-robot backport to 4.6

**Comment by JFlath** [comment]
@cb-docs-robot backport to 4.1

**Comment by JFlath** [comment]
@cb-docs-robot backport to 4.0

**Comment by JFlath** [comment]
@cb-docs-robot backport to ALL THE THINGS!

**Comment by JFlath** [comment]
@mattcarabine I may have broken things... Sorry

**Comment by mattcarabine** [comment]
@cb-docs-robot backport to 4.5

**Comment by mattcarabine** [comment]
There is a typo.... @JFlath "affect" should be "effect"

**Comment by mattcarabine** [comment]
Once it's fixed I will re-backport
:D

**Comment by JFlath** [comment]
I blame everyone but myself!


...gimme a sec

**Comment by mattcarabine** [comment]
@cb-docs-robot backport to 4.5

**Comment by mattcarabine** [comment]
@cb-docs-robot backport to 4.6

**Pull request merged**
