### PR TITLE
PHP: add link to pecl installation

### PR DESCRIPTION
**Pull request by avsej**
/cc @arun-gupta

### CODE REVIEW

**Comment by arun-gupta** [comment]
Installing PECL gives the following error:

```
sudo pecl install couchbase
Did not download optional dependencies: pecl/igbinary, use --alldeps to download automatically
pecl/couchbase can optionally use package "pecl/igbinary"
downloading couchbase-2.2.0.tgz ...
Starting to download couchbase-2.2.0.tgz (59,251 bytes)
..............done: 59,251 bytes
46 source files, building
running: phpize
grep: /usr/include/php/main/php.h: No such file or directory
grep: /usr/include/php/Zend/zend_modules.h: No such file or directory
grep: /usr/include/php/Zend/zend_extensions.h: No such file or directory
Configuring for:
PHP Api Version:
Zend Module Api No:
Zend Extension Api No:
Cannot find autoconf. Please check your autoconf installation and the
$PHP_AUTOCONF environment variable. Then, rerun this script.

ERROR: `phpize' failed
```

Found I need to install `autoconf` and so did:

```
brew install autoconf
==> Downloading https://homebrew.bintray.com/bottles/autoconf-2.69.el_capitan.bottle.4.tar.gz
######################################################################## 100.0%
==> Pouring autoconf-2.69.el_capitan.bottle.4.tar.gz
==> Caveats
Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/autoconf
==> Summary
🍺  /usr/local/Cellar/autoconf/2.69: 70 files, 3.0M
```

Now `pecl install couchbase` gives the following error:

```
sudo pecl install couchbase
Did not download optional dependencies: pecl/igbinary, use --alldeps to download automatically
pecl/couchbase can optionally use package "pecl/igbinary"
downloading couchbase-2.2.0.tgz ...
Starting to download couchbase-2.2.0.tgz (59,251 bytes)
..............done: 59,251 bytes
46 source files, building
running: phpize
grep: /usr/include/php/main/php.h: No such file or directory
grep: /usr/include/php/Zend/zend_modules.h: No such file or directory
grep: /usr/include/php/Zend/zend_extensions.h: No such file or directory
Configuring for:
PHP Api Version:
Zend Module Api No:
Zend Extension Api No:
building in /private/tmp/pear/install/pear-build-rootekFdlm/couchbase-2.2.0
running: /private/tmp/pear/install/couchbase/configure --with-php-config=/usr/bin/php-config
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-apple-darwin15.3.0
checking host system type... x86_64-apple-darwin15.3.0
checking target system type... x86_64-apple-darwin15.3.0
checking for PHP prefix... /usr
checking for PHP includes... -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib
checking for PHP extension directory... /usr/lib/php/extensions/no-debug-non-zts-20121212
checking for PHP installed headers prefix... /usr/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... no
checking for nawk... no
checking for awk... awk
checking if awk is broken... no
checking whether to enable Couchbase support... yes, shared
checking wheter to use system FastLZ bibrary... no
checking for libcouchbase in default path... found in /usr/local
checking for ld used by cc... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
checking if the linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) is GNU ld... no
checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm
checking whether ln -s works... yes
checking how to recognize dependent libraries... pass_all
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking the maximum length of command line arguments... 196608
checking command to parse /usr/bin/nm output from cc object... ok
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking if cc supports -fno-rtti -fno-exceptions... yes
checking for cc option to produce PIC... -fno-common
checking if cc PIC flag -fno-common works... yes
checking if cc static flag -static works... no
checking if cc supports -c -o file.o... yes
checking whether the cc linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin15.3.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no

creating libtool
appending configuration tag "CXX" to libtool
configure: creating ./config.status
config.status: creating config.h
running: make
/bin/sh /private/tmp/pear/install/pear-build-rootekFdlm/couchbase-2.2.0/libtool --mode=compile cc  -I. -I/private/tmp/pear/install/couchbase -DPHP_ATOM_INC -I/private/tmp/pear/install/pear-build-rootekFdlm/couchbase-2.2.0/include -I/private/tmp/pear/install/pear-build-rootekFdlm/couchbase-2.2.0/main -I/private/tmp/pear/install/couchbase -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/usr/local/include  -DHAVE_CONFIG_H  -g -O2   -c /private/tmp/pear/install/couchbase/bucket.c -o bucket.lo
mkdir .libs
 cc -I. -I/private/tmp/pear/install/couchbase -DPHP_ATOM_INC -I/private/tmp/pear/install/pear-build-rootekFdlm/couchbase-2.2.0/include -I/private/tmp/pear/install/pear-build-rootekFdlm/couchbase-2.2.0/main -I/private/tmp/pear/install/couchbase -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/usr/local/include -DHAVE_CONFIG_H -g -O2 -c /private/tmp/pear/install/couchbase/bucket.c  -fno-common -DPIC -o .libs/bucket.o
In file included from /private/tmp/pear/install/couchbase/bucket.c:17:
/private/tmp/pear/install/couchbase/couchbase.h:29:10: fatal error: 'php.h' file not found
#include <php.h>
         ^
1 error generated.
make: *** [bucket.lo] Error 1
ERROR: `make' failed
```

Any idea?

**Comment by avsej** [comment]
how did you install PHP? it seems like it cannot find the headers. are you using php from the OS X? I would recommend to install php from homebrew

**Comment by arun-gupta** [comment]
`brew install php56 --with-pear` is failing with:

```
==> Installing php56 from homebrew/php
==> Downloading https://php.net/get/php-5.6.24.tar.bz2/from/this/mirror
==> Downloading from https://secure.php.net/distributions/php-5.6.24.tar.bz2
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/php56/5.6.24 --localstatedir=/usr/local/var --sysconfdir=/usr/loca
Last 15 lines from /Users/arungupta/Library/Logs/Homebrew/php56/01.configure:
checking whether to use system default cipher list instead of hardcoded value... no
checking for krb5-config... /usr/bin/krb5-config
checking for DSA_get_default_method in -lssl... no
checking for X509_free in -lcrypto... yes
checking for RAND_egd... no
checking for pkg-config... no
checking for OpenSSL version... >= 0.9.6
checking for CRYPTO_free in -lcrypto... yes
checking for SSL_CTX_set_ssl_version in -lssl... yes
checking for PCRE library to use... bundled
checking whether to enable the SQLite3 extension... yes
checking bundled sqlite3 library... yes
checking for ZLIB support... yes
checking if the location of ZLIB install directory is defined... no
configure: error: Cannot find libz

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-php/issues

These open issues may also help:
Updated php56-protobuf version. https://github.com/Homebrew/homebrew-php/pull/3272
brew install php56 https://github.com/Homebrew/homebrew-php/issues/2760
Make error php56 https://github.com/Homebrew/homebrew-php/issues/1842
PHP56 required for composer https://github.com/Homebrew/homebrew-php/issues/2796
failed to install php56-pthreads https://github.com/Homebrew/homebrew-php/issues/2768
Failed to install/reinstall php56-http https://github.com/Homebrew/homebrew-php/issues/2711
Every update of php56 force me to reinstall php56-intl and php56-mcrypt with --build-from-source https://github.com/Homebrew/homebrew-php/issues/2440
Can't install php56-mcrypt https://github.com/Homebrew/homebrew-php/issues/2452
Fails to Install Php56 with Imap Extensiton https://github.com/Homebrew/homebrew-php/issues/2703
I can't find php56_pdo! https://github.com/Homebrew/homebrew-php/issues/2706
Adds a new php70-gearman formula that updates php56-gearman https://github.com/Homebrew/homebrew-php/pull/3120
"brew upgrade" fails: php56 conflicting with php70 when upgrading phpmyadmin https://github.com/Homebrew/homebrew-php/issues/2945
Why does wp-cli formula try to install php56 if php70 is already there? https://github.com/Homebrew/homebrew-php/issues/3179
PHP56 can't launch as root, with nginx 500 Internal Server Error? https://github.com/Homebrew/homebrew-php/issues/2709
```

**Comment by avsej** [comment]
> checking if the location of ZLIB install directory is defined... no
> configure: error: Cannot find libz
maybe install libz?

**Comment by arun-gupta** [comment]
How to install?

```
brew install libz
Error: No available formula with the name "libz" 
==> Searching for similarly named formulae...
These similarly named formulae were found:
libzdb                               libzip                               libzzip                            
To install one of them, run (for example):
  brew install libzdb
==> Searching taps...
Error: No formulae found in taps.
==> You haven't updated Homebrew in a while.
A formula for libz might have been added recently.
Run `brew update` to get the latest Homebrew updates!
```

**Comment by avsej** [comment]
there is a ticket about it: https://github.com/Homebrew/homebrew-php/issues/205

**Comment by arun-gupta** [comment]
Is `zlib` the same as `libz`?

That didn't work for me:

```
 > brew untap homebrew/dupes
Untapping homebrew/dupes... (103 files, 119.8K)
Untapped 38 formulae
 > brew tap homebrew/dupes
==> Tapping homebrew/dupes
Cloning into '/usr/local/Library/Taps/homebrew/homebrew-dupes'...
remote: Counting objects: 42, done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 42 (delta 0), reused 8 (delta 0), pack-reused 0
Unpacking objects: 100% (42/42), done.
Checking connectivity... done.
Tapped 38 formulae (103 files, 119.9K)
Downloads > brew install libz
Error: No available formula with the name "libz" 
==> Searching for similarly named formulae...
These similarly named formulae were found:
libzdb                               libzip                               libzzip                            
To install one of them, run (for example):
  brew install libzdb
==> Searching taps...
Error: No formulae found in taps.
==> You haven't updated Homebrew in a while.
A formula for libz might have been added recently.
Run `brew update` to get the latest Homebrew updates!
```

**Comment by avsej** [comment]
libz is shared object, zlib is the project name. BTW you could remove php and `untap homebrew/homebrew-php` for now and `tap avsej/homebrew-php` and then `brew install php56-couchbase`, if it is easier for you. But note that it only because people are delaying merge of my PR https://github.com/Homebrew/homebrew-php/pull/3381

**Comment by amarantha-k** [comment]
@avsej This PR was opened after the 4.5 updates were published on Friday. It will be picked up in the next cycle, scheduled for 7/26.

**Comment by avsej** [comment]
@amarantha-k I'm okay with it

**Comment by avsej** [comment]
So let me recap the conversation,

Basically there are two ways to install extension:

1) install pecl using official guide, but in this case there are more things to watch after (like which php distribution the pecl will remember, how to upgrade php and extension itself and so on). So I would not recommend this way (so @amarantha-k please hold off merging this PR)

2) the second way is purely based on homebrew, because currently it is preferred way to deal with PHP distributions, and couchbase extension already available for all major PHP versions. But when I've been doing 2.2.0 release, I forgot about this repo (homebrew/homebrew-php) and didn't update the formulas. The update still in PR mode now, but I hope it will be merged soon. For future releases I will send update as a part of release process, so users will get this in time. 

Current version of the docs already describes the second option, so essentially no updates necessary:
http://developer.couchbase.com/documentation/server/current/sdk/php/start-using-sdk.html#story-h2-2

@arun-gupta while the PR from (2) in review, you could use my fork just to verify process:

```bash
brew untap homebrew/homebrew-php
brew tap avsej/homebrew-php
brew install php56-couchbase
```

**Comment by ingenthr** [comment]
And note that that homebrew line was added possibly after this issue is open.

That said, it's a bit ambiguous there since it mentions pecl in that Mac OS section.  Maybe you can break it down into a "preferred method" and a "pecl driven" method?  That might make flow clearer.  Chat with @mnunberg about how to set up headings if you're unsure.

**Comment by arun-gupta** [comment]
@avsej when do you expect formal repo to be updated?

Where can I find the PR from (2)?

The recommended workaround is not working for me:

```
 > brew untap homebrew/homebrew-php
Untapping homebrew/php... (616 files, 1.1M)
Untapped 576 formulae
 > brew tap avsej/homebrew-php
==> Tapping avsej/php
Cloning into '/usr/local/Library/Taps/avsej/homebrew-php'...
remote: Counting objects: 601, done.
remote: Compressing objects: 100% (369/369), done.
remote: Total 601 (delta 308), reused 490 (delta 230), pack-reused 0
Receiving objects: 100% (601/601), 293.57 KiB | 549.00 KiB/s, done.
Resolving deltas: 100% (308/308), done.
Checking connectivity... done.
Tapped 576 formulae (616 files, 1.1M)
 > brew install php56-couchbase
==> Installing php56-couchbase from avsej/php
==> Installing dependencies for avsej/php/php56-couchbase: php56
==> Installing avsej/php/php56-couchbase dependency: php56
==> Downloading https://homebrew.bintray.com/bottles-php/php56-5.6.24.el_capitan.bottle.12.tar.gz
Already downloaded: /Users/arungupta/Library/Caches/Homebrew/php56-5.6.24.el_capitan.bottle.12.tar.gz
==> Pouring php56-5.6.24.el_capitan.bottle.12.tar.gz
==> Caveats
To enable PHP in Apache add the following to httpd.conf and restart Apache:
    LoadModule php5_module    /usr/local/opt/php56/libexec/apache2/libphp5.so

The php.ini file can be found in:
    /usr/local/etc/php/5.6/php.ini

✩✩✩✩ Extensions ✩✩✩✩

If you are having issues with custom extension compiling, ensure that
you are using the brew version, by placing /usr/local/bin before /usr/sbin in your PATH:

      PATH="/usr/local/bin:$PATH"

PHP56 Extensions will always be compiled against this PHP. Please install them
using --without-homebrew-php to enable compiling against system PHP.

✩✩✩✩ PHP CLI ✩✩✩✩

If you wish to swap the PHP you use on the command line, you should add the following to ~/.bashrc,
~/.zshrc, ~/.profile or your shell's equivalent configuration file:

      export PATH="$(brew --prefix homebrew/php/php56)/bin:$PATH"

✩✩✩✩ FPM ✩✩✩✩

To launch php-fpm on startup:
    mkdir -p ~/Library/LaunchAgents
    cp /usr/local/opt/php56/homebrew.mxcl.php56.plist ~/Library/LaunchAgents/
    launchctl load -w ~/Library/LaunchAgents/homebrew.mxcl.php56.plist

The control script is located at /usr/local/opt/php56/sbin/php56-fpm

OS X 10.8 and newer come with php-fpm pre-installed, to ensure you are using the brew version you need to make sure /usr/local/sbin is before /usr/sbin in your PATH:

  PATH="/usr/local/sbin:$PATH"

You may also need to edit the plist to use the correct "UserName".

Please note that the plist was called 'homebrew-php.josegonzalez.php56.plist' in old versions
of this formula.

To have launchd start avsej/php/php56 now and restart at login:
  brew services start avsej/php/php56
==> Summary
🍺  /usr/local/Cellar/php56/5.6.24: 331 files, 48.9M
==> Installing avsej/php/php56-couchbase
==> Downloading https://pecl.php.net/get/couchbase-2.2.0.tgz
######################################################################## 100.0%
==> /usr/local/opt/php56/bin/phpize
Last 15 lines from /Users/arungupta/Library/Logs/Homebrew/php56-couchbase/01.phpize:
2016-07-26 08:24:20 -0700

/usr/local/opt/php56/bin/phpize

/usr/local/opt/php56/bin/phpize: line 61: /usr/local/Library/Homebrew/shims/super/sed: No such file or directory
/usr/local/opt/php56/bin/phpize: line 62: /usr/local/Library/Homebrew/shims/super/sed: No such file or directory
/usr/local/opt/php56/bin/phpize: line 63: /usr/local/Library/Homebrew/shims/super/sed: No such file or directory
Configuring for:
PHP Api Version:        
Zend Module Api No:     
Zend Extension Api No:  
/usr/local/opt/php56/bin/phpize: line 155: /usr/local/Library/Homebrew/shims/super/sed: No such file or directory
autoheader: error: AC_CONFIG_HEADERS not found in configure.in

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/avsej/homebrew-php/issues
```

**Comment by avsej** [comment]
Could you reinstall php56?

**Comment by amarantha-k** [comment]
@avsej Let me know when this PR is good to be merged.

**Comment by avsej** [comment]
I will let you know, but let's not merge it yet

**Comment by arun-gupta** [comment]
@avsej we've installed PHP a couple of ways. Can you list the exact steps that need to be followed to get this working?

**Comment by arun-gupta** [comment]
@avsej any updates on this? I'd like to finish the starter kit on this.

**Comment by avsej** [comment]
On another PR #708 we updated the start using section and beleive it's good.  This PR should probably be closed.  As to the issue you're into, it appears to be related to homebrew being in an undefined state.  Probably best to either run `brew doctor` or just remove and reinstall homebrew. 

Or to make it even better and reproducible for all users (not only MacOS), I would start guide from something like 

```
docker run -ti php:7
```

**Comment by avsej** [comment]
sample `Dockerfile`:

```Dockerfile
FROM php:7

# general dependencies
RUN apt-get update && apt-get install -y zlib1g-dev lsb-release build-essential

# libcouchbase
RUN curl -O http://packages.couchbase.com/releases/couchbase-release/couchbase-release-1.0-2-amd64.deb && dpkg -i couchbase-release-1.0-2-amd64.deb
RUN apt-get update && apt-get install -y libcouchbase-dev libcouchbase2-bin 

# couchbase php extension
RUN pecl install couchbase
RUN echo "extension=couchbase.so" > /usr/local/etc/php/conf.d/99-couchbase.ini

# demonstate that it has been loaded
RUN php -i | grep couchbase
```

Build the image and tag it as `demo`:

```
docker build -t demo .
```

Run our demo (which has PHP7 and couchbase extension)

```
docker run -ti demo /bin/bash
```

**Pull request closed without merging**
