### PR TITLE
added Adaptive Index

### PR DESCRIPTION
**Pull request by guyklages**

### CODE REVIEW

**Comment by guyklages** [comment]
@cb-docs-robot backport to 4.5

**Comment by guyklages** [comment]
@cb-docs-robot backport to 4.6

**Comment by guyklages** [comment]
@cb-docs-robot backport to 4.5

**Comment by guyklages** [comment]
@cb-docs-robot backport to 4.6

**Comment by mattcarabine** [comment]
@guyklages Out of interest, why do you want to backport this content? I thought Adaptive indexes are new for 5.0?

**Pull request merged**
