### PR TITLE
SDK Tutorial for 4.5

### PR DESCRIPTION
**Pull request by simonbasle**
This is the tutorial based on `try-cb-frontend` v2.0.0, for Couchbase Server 4.5.

It currently includes the java SDK specific page based on `try-cb-java` v2.0.0 as well.

@ingenthr should other SDKs add their own specific page to this PR or can it be merged?

### CODE REVIEW

**Comment by ingenthr** [comment]
Thanks @simonbasle.  I'll chat through this with @1tylermitchell and we'll determine how to handle.

**Comment by amarantha-k** [comment]
@simonbasle and @ingenthr 
Please let me know if this PR is ready to be merged and published.

**Comment by simonbasle** [comment]
@amarantha-k no, please wait for @ingenthr confirmation before merging this, thanks ;)

**Comment by MikeGoldsmith** [comment]
Added .NET documentation in same vein as Java documentation.

**Comment by 1tylermitchell** [comment]
Still pending docs for PHP, Nodejs, Go (and boilerplate for C)

**Comment by 1tylermitchell** [comment]
@MikeGoldsmith can you please add a short bootstrap/connect example for dotnet.  I commented out a heading for it you'll see after Walking Through the API section.

**Comment by mattcarabine** [comment]
@MikeGoldsmith Also make sure you do a pull beforehand (I just updated the dotnet page)

**Comment by mattcarabine** [comment]
@1tylermitchell my review is done. Once @MikeGoldsmith's changes are in we should be good to merge!

**Comment by MikeGoldsmith** [comment]
@1tylermitchell @mattcarabine updated the section as requested

**Comment by mattcarabine** [comment]
@1tylermitchell will let you have a last once over. Let me know when we're ready to and I'll backport this to 4.6 too.

**Comment by mattcarabine** [comment]
@cb-docs-robot backport to 4.6

**Pull request merged**
