### PR TITLE
Upgd 02

### PR DESCRIPTION
**Pull request by tonyjhillman**

### CODE REVIEW

**Comment by mattcarabine** [comment]
@cb-docs-robot rebuild

**Comment by 1tylermitchell** [comment]
Add Matt as reviewer, as he found I was mistaken in some of my corrections.

**Comment by ingenthr** [comment]
Unfortunately, your changes here were wrong @1tylermitchell.  The only situations where you are *required* to upgrade the sdk are if
1) you're starting with a new bucket on a 5.0 system, and choose to have a username that is not the same as the bucket name.  also, 5.0 always requires a password, or…
2) you want to have an actual username (versions prior to 5.0 haven't such a concept) separate from the bucket name and leverage more of the RBAC features

Can you help get this corrected?

**Comment by tonyjhillman** [comment]
Merge deferred until DOC-S2-Nov03.

**Comment by tonyjhillman** [comment]
See DOC-2568.

**Comment by ingenthr** [comment]
How were the problems addressed @tonyjhillman ?  I looked at https://issues.couchbase.com/browse/DOC-2568 and it doesn't say anything about correcting the parts that are wrong here.

**Pull request closed without merging**
