### PR TITLE
UGNOTE4dot5: Added forward-pointing note, alerting developer to 5.0 a…

### PR DESCRIPTION
**Pull request by tonyjhillman**
…uthentication

### CODE REVIEW

**Comment by 1tylermitchell** [comment]
Looks good.

**Comment by tonyjhillman** [comment]
Merge deferred until DOC-S2-Nov03, due to issues with UPGD-02.

**Comment by tonyjhillman** [comment]
See DOC-2568.

**Comment by 1tylermitchell** [comment]
thanks for these changes.. it is clearer now

**Pull request merged**
