### PR TITLE
DOC-2116: Correct Cluster Init Rest Command

### PR DESCRIPTION
**Pull request by JFlath**

### CODE REVIEW

**Comment by JFlath** [comment]
@cb-docs-robot backport to 4.5

**Comment by mattcarabine** [comment]
@JFlath I can manually backport this. Cheers for the contribution.

**Comment by mattcarabine** [comment]
@cb-docs-robot backport to master

**Comment by mattcarabine** [comment]
🤦‍♂️

**Comment by mattcarabine** [comment]
leaving open to remind me to backport

**Comment by mattcarabine** [comment]
@cb-docs-robot backport to 4.5

**Pull request merged**
