### PR TITLE
CBSE notes; UPSERT clean-up; INSERT codeblocks

### PR DESCRIPTION
**Pull request by guyklages**

### CODE REVIEW

**Comment by mattcarabine** [comment]
Hey @guyklages I don't think the approach here is really right. For 4.5 + 4.6 content we should add it to the 4.5 and 4.6 docs themselves, since people aren't going to be reading the 5.0 docs if they're not using it.

**Comment by mattcarabine** [comment]
Imo we should document the 5.0 behaviour in 5.0 and then make a separate change for both 4.5 and 4.6 which covers the behaviour in those versions.

**Comment by amarantha-k** [comment]
Agree with Matt - we need to add 5.0 information in 5.x docs. The 4.x specific note in this page needs to be submitted separately - http://docs-build.sc.couchbase.com/server/1667/monitoring/monitoring-n1ql-query.html

**Comment by amarantha-k** [comment]
Closing as this change was submitted as part of a different PR.

**Pull request closed without merging**
