### PR TITLE
Bump Java to 2.3.5

### PR DESCRIPTION
**Pull request by daschl**
ping @amarantha-k

### CODE REVIEW

**Comment by amarantha-k** [comment]
@daschl Master branch is now being used for Server 4.6. I suppose you want this change on Server 4.5 (4.5 branch). Please confirm.

**Comment by daschl** [comment]
I'm good with that, but it should probably in both?

**Comment by amarantha-k** [comment]
Since it's a third digit update, it'll be included with the current version of the server docs (4.5) for now. 
The 4.6 GA docs will include the latest SDK versions. For DP, a subset of the documentation is planned to be delivered.

**Comment by amarantha-k** [comment]
Closing this PR as the change has been cherry-picked on 4.5 branch.

**Pull request closed without merging**
