### PR TITLE
DOC-2034 - Update FD Limit Recommendation

### PR DESCRIPTION
**Pull request by JFlath**
Have updated this on this branch only, but needs changing everywhere - @mattcarabine is this where we can use your backport magic?

### CODE REVIEW

**Comment by mattcarabine** [comment]
@cb-docs-robot rebuild

**Comment by mattcarabine** [comment]
Wow that page is a mess... can you check the draft please @JFlath and lemme know if you're happy with the changes. If so, will backport and merge.

**Comment by JFlath** [comment]
Thinking about it, it should probably be:

```
ulimit -n 40960
ulimit -c unlimited 
```

rather than

```
> ulimit -n 40960 ulimit -c unlimited 
```

I was a bit to blinkered making the change :P. What's your preferred way for me to amend that? Or is another commit fine - are you going to squash?

**Comment by mattcarabine** [comment]
I'd prefer it if you did a `commit --amend` and then a force push please!

**Comment by JFlath** [comment]
I can do git, me!

...dita, not so much. Give me a sec

**Comment by JFlath** [comment]
That looks better :)

**Comment by mattcarabine** [comment]
@cb-docs-robot backport to 4.6

**Comment by mattcarabine** [comment]
@cb-docs-robot backport to 4.5

**Comment by mattcarabine** [comment]
@cb-docs-robot backport to 4.1

**Pull request merged**
