### PR TITLE
Add note explaining how to enable IPv6 support

### PR DESCRIPTION
**Pull request by dnault**

### CODE REVIEW

**Comment by amarantha-k** [comment]
@jamiltz @avsej @daschl Waiting for your review/approval before I merge this one.

**Comment by amarantha-k** [comment]
Sorry - should have remembered before I merged! Since IPv6 is a 5.5 feature, just want to confirm that we want this change to be on Vulcan branch and not master( 5.1).

**Comment by dnault** [comment]
The release notes for the Kafka connector should be independent of Couchbase Server version.

**Comment by amarantha-k** [comment]
I understand. However, due the way the docs are currently organized (which will change soon) the connector docs are included as part of a specific Server version.

**Pull request merged**
