### PR TITLE
JCBC-1044 - add a note on SELECT RAW.

### PR DESCRIPTION
**Pull request by daschl**

### CODE REVIEW

**Comment by daschl** [comment]
ping @mattcarabine, needs backport :)

**Comment by mattcarabine** [comment]
@cb-docs-robot rebuild

**Comment by mattcarabine** [comment]
@cb-docs-robot rebuild

**Comment by mattcarabine** [comment]
@cb-docs-robot backport to 4.6

**Comment by mattcarabine** [comment]
@cb-docs-robot backport to master

**Pull request merged**
