### PR TITLE
Bump for 2.4.6 SDK

### PR DESCRIPTION
**Pull request by daschl**

### CODE REVIEW

**Comment by daschl** [comment]
@mattcarabine needs backporting too :) thanks!

**Comment by mattcarabine** [comment]
Need an update to the API reference URL too?

**Comment by daschl** [comment]
@mattcarabine ah yes that would be great too - can you handle that or should I submit a new PR from the website?

**Comment by mattcarabine** [comment]
@daschl Would you mind doing it once I've merged this change?

**Comment by mattcarabine** [comment]
@cb-docs-robot backport to master

**Comment by mattcarabine** [comment]
@daschl Should be good to go for the api ref update!

**Pull request merged**
