### PR TITLE
DOC-2683: fixed 2 typos in install-swap-space.dita

### PR DESCRIPTION
**Pull request by orthogonal3**
Fixed 2 typos in install-swap-space.dita for DOC-2683

2x "swappines" -> "swappiness"

### CODE REVIEW

**Comment by JFlath** [comment]
@cb-docs-robot backport to 4.5

**Comment by JFlath** [comment]
@cb-docs-robot backport to 4.1

**Comment by JFlath** [comment]
@cb-docs-robot backport to 4.0

**Comment by mattcarabine** [comment]
This was already fixed in master. Cheers for the contribution Phil! Hopefully the first of many.

**Pull request merged**
