### PR TITLE
spark 1.2.1 docs update

### PR DESCRIPTION
**Pull request by daschl**
ping @marijadjovanovic @amarantha-k (and @ingenthr FYI)

can you please merge and publish? This needs to go into all places where spark 1.2 is published (4.0, 4.1 and 4.5?)

thanks!

### CODE REVIEW

**Comment by daschl** [comment]
what happened here with the rebase? anyways, I guess this also needs to go into 4.5 now since its released

**Comment by daschl** [comment]
ping @ingenthr @marijadjovanovic @amarantha-k

**Comment by amarantha-k** [comment]
@daschl Can you rebase your PR over the updated master and resubmit please?

**Comment by ingenthr** [comment]
I can't update @daschl's branch, so I've rebased it and it's in PR #671

**Pull request closed without merging**
