### PR TITLE
DOC-1833: Fix active/replica eviction percentages

### PR DESCRIPTION
**Pull request by mattcarabine**

### CODE REVIEW

**Comment by amarantha-k** [comment]
@mattcarabine Isn't this a repeat of the previous sentence? 
"Evictions then occur until the memory usage reaches the low watermark, both active and replica documents are evicted during this process."

**Comment by mattcarabine** [comment]
@amarantha-k Yeah you're right, that was there before and I hadn't noticed when cleaning it up. Will repush the commit.

**Comment by mattcarabine** [comment]
Fixed.

**Comment by amarantha-k** [comment]
@mattcarabine Thanks!

**Pull request merged**
