### PR TITLE
PHP operations and using

### PR DESCRIPTION
**Pull request by avsej**
@mnunberg @amarantha-k @marijadjovanovic

### CODE REVIEW

**Comment by mnunberg** [comment]
This is good to merge. If possible, example output should be smaller or truncated, especially in getting started, but I think it's better to merge and take care of this later.

Same thing with the download links: That information will end up being on a different page.

**Comment by avsej** [comment]
@mnunberg what I can use as a reference for download links?

**Comment by mnunberg** [comment]
I'm not sure. I was just giving a heads up. I suppose it's fine for now.

**Comment by ingenthr** [comment]
Rebased and applied some minor fixes.

**Pull request closed without merging**
