### PR TITLE
PHP: properly close section tag

### PR DESCRIPTION
**Pull request by avsej**
Also add steps for homebrew/homebrew-php

### CODE REVIEW

**Comment by ingenthr** [comment]
Updated with another change and issued a new PR

**Comment by arun-gupta** [comment]
Can you add instructions to install PECL? Otherwise these are incomplete.

**Comment by avsej** [comment]
@arun-gupta I don't think we should describe it in SDK getting started as it might outdate.

@ingenthr maybe just linking to https://pear.php.net/manual/en/installation.getting.php would be enough? pecl comes with most of the distributions anyway.

**Comment by avsej** [comment]
It is pretty easy to google it. I don't want to support installation issues of the pecl on MacOS, because there are several ways to do it. And it requires extra work when people need to have multiple PHP (like setting PHP_PEAR_PHP_BIN properly).

I would expect that people know how to install pecl extensions, and all we need to tell them is how to install couchbase specific dependencies, and the extensions itself.

**Comment by arun-gupta** [comment]
Adding a link to the standard install instructions is fine.

**Pull request closed without merging**
