### PR TITLE
java spring compat table

### PR DESCRIPTION
**Pull request by daschl**
ping @simonbasle @ingenthr @ToddGreenstein

### CODE REVIEW

**Comment by ingenthr** [comment]
@ToddGreenstein can you review and decide how to commonize the table, then reassign it back to me?

**Comment by simonbasle** [comment]
LGTM, as discussed with Michael, would maybe say "Compatible (no N1QL)" for 1.4.x and server version 4.0+

**Comment by ToddGreenstein** [comment]
Rolled up into https://github.com/couchbase/docs-cb4/pull/639

**Comment by amarantha-k** [comment]
Closing as per Todd's comment. This has been rolled up into #639

**Pull request closed without merging**
