### PR TITLE
Analytics

### PR DESCRIPTION
**Pull request by sigmod**

### CODE REVIEW

**Comment by sigmod** [comment]
@cb-docs-robot build analytics

**Comment by sigmod** [comment]
@mattcarabine  it looks PR-build is hanging for this PR?

**Comment by mattcarabine** [comment]
@sigmod it is designed to ignore all PRs with 'analytics' in the title or description (for now).

**Comment by mattcarabine** [comment]
Removed it as it is blocking merging

**Comment by mattcarabine** [comment]
@cb-docs-robot rebuild

**Comment by mattcarabine** [comment]
@cb-docs-robot build analytics

**Comment by sigmod** [comment]
@cb-docs-robot build analytics

**Comment by westmann** [comment]
@cb-docs-robot build analytics

**Comment by mattcarabine** [comment]
Looks fine to me if you are happy with it @sigmod and @westmann

**Comment by sigmod** [comment]
Thanks, @mattcarabine, could your merge it?

**Pull request merged**
