### PR TITLE
Update rbac.dita

### PR DESCRIPTION
**Pull request by waffledonkey**
the roles seem to have changed from `cluster_admin` to `admin` and `bucket_admin` to `bucket_full_access`.  I was unsure how it's logged (line 273) so that may still be incorrect.

### CODE REVIEW

**Comment by RichardSmedley** [comment]
Hi there. Thanks for the PR - they're always appreciated. :-)

In this case the current doc is correct for the stated rôles: e.g. cluster and bucket administrator in line 148.

What was the problem that you were trying to solve, here? I'm sure someone on the team can help.

**Comment by waffledonkey** [comment]
I was trying to create an RBAC user and assign them roles (5.1.1) and did so as the docs prescribed 

curl -X PUT -d "name=Catalog User" -d "roles=cluster_admin,bucket_admin[catalog]" -d "password=REDACTED" -H "Content-Type: application/x-www-form-urlencoded" --user REDACTED:REDACTED http://localhost:8091/settings/rbac/users/local/REDACTED

which resulted in an error:

"Cannot assign roles to user because the following roles are unknown, malformed or role parameters are undefined: [bucket_admin[catalog],cluster_admin]"

I then dumped the roles using:

curl -X GET --user REDACTED:REDACTED http://localhost:8091/settings/rbac/roles | jsonlint

and got:

[
  {
    "role": "bucket_full_access",
    "bucket_name": "*",
    "name": "Bucket Full Access",
    "desc": "Full access to bucket data",
    "ce": true
  },
  {
    "role": "bucket_full_access",
    "bucket_name": "default",
    "name": "Bucket Full Access",
    "desc": "Full access to bucket data",
    "ce": true
  },
  {
    "role": "ro_admin",
    "name": "Read Only Admin",
    "desc": "Can view ALL cluster features.",
    "ce": true
  },
  {
    "role": "admin",
    "name": "Admin",
    "desc": "Can manage ALL cluster features including security.",
    "ce": true
  }
]

seeing that the role names were "admin" and "bucket_full_access" I then changed my API call accordingly first just testing bucket_full_access but keeping cluster_admin

curl -X PUT -d "name=Catalog User" -d "roles=cluster_admin,bucket_full_access[catalog]" -d "password=REDACTED" -H "Content-Type: application/x-www-form-urlencoded" --user REDACTED:REDACTED http://localhost:8091/settings/rbac/users/local/REDACTED

which resulted in the error being isolated to the cluster_admin role

"Cannot assign roles to user because the following roles are unknown, malformed or role parameters are undefined: [cluster_admin]"

I then changed the query to set both roles to what the system is saying they are (bucket_full_access and admin) not what the docs say they are (bucket_admin and cluster_admin)

curl -X PUT -d "name=Catalog User" -d "roles=bucket_full_access[catalog],admin" -d "password=REDACTED" -H "Content-Type: application/x-www-form-urlencoded" --user REDACTED:REDACTED http://localhost:8091/settings/rbac/users/local/REDACTED

I recognize that admin and bucket_full_access are redundant, I was just testing to confirm.

which worked correctly.  Then because I was already on the docs page and felt I'd tested adequately I updated the docs.  While you're certainly in a better position to know than I am, what makes you believe the roles have not changed because I kind of feel like my evidence that they have is fairly complete/convincing.

**Comment by waffledonkey** [comment]
It seems that the community edition has more limited roles than the enterprise edition and/or is ahead/behind on such changes.

**Comment by RichardSmedley** [comment]
Apologies for the confusion over the Community vs Enterprise Edition.

While the documentation does cover this [elsewhere](https://developer.couchbase.com/documentation/server/current/security/security-authorization.html), I see that the REST API is lacking any such mention. I'll be changing that today for relevant versions of the docs (5.0, 5.1, and 5.5beta), and the changes will appear in the docs in the coming days as the site gets built again: [DOC-3776](https://issues.couchbase.com/browse/DOC-3776)

Thank you again for bringing it to the team's attention, and sorry that it left you wandering down the rabbit hole for a while!

**Pull request closed without merging**
