### PR TITLE
GTS-0001: New organization and content for section

### PR DESCRIPTION
**Pull request by tonyjhillman**
Revised Getting Started section, with Docker install, Workbench query, and node.js code example

### CODE REVIEW

**Comment by tonyjhillman** [comment]
@cb-docs-robot rebuild

**Comment by mattcarabine** [comment]
@cb-docs-robot rebuild

**Comment by tonyjhillman** [comment]
@cb-docs-robot rebuild

**Comment by mattcarabine** [comment]
Weird that the bot didn't print the URL - here it is http://docs-build.sc.couchbase.com:8080/job/Server/job/pull-requests/job/build-pr/346/parsed_console/

**Comment by tonyjhillman** [comment]
@cb-docs-robot rebuild

**Comment by tonyjhillman** [comment]
@cb-docs-robot rebuild

**Comment by tonyjhillman** [comment]
@cb-docs-robot rebuild

**Comment by tonyjhillman** [comment]
@cb-docs-robot rebuild

**Comment by mattcarabine** [comment]
@tonyjhillman this is failing because there is a merge conflict due to https://github.com/couchbase/docs-cb4/commit/460f8cf91b78a8bba3088ce59f31cc87d0a3d2d6#diff-f80df2e41da0edd983cddf3c09bb1d5b.

You will need to rebase master branch onto GTS-0001:

```
git checkout GTS-0001
git fetch couchbase #(or whatever you called the remote)
git rebase couchbase/master
```

That rebase will fail due to a conflict, just resolve the merge conflict and then continue with the rebase, then (force) push it back up to github - it should work then.

Let me know if you get stuck and want me to take a look instead.

**Pull request merged**
