### PR TITLE
Fix spelling errors

### PR DESCRIPTION
**Pull request by GauthamBanasandra**

### CODE REVIEW

**Comment by mattcarabine** [comment]
@cb-docs-robot rebuild

**Comment by mattcarabine** [comment]
Again, thanks for the contribution @GauthamBanasandra! I'll get this change backported and merged.

**Comment by mattcarabine** [comment]
@cb-docs-robot backport to 4.5

**Comment by mattcarabine** [comment]
@cb-docs-robot backport to master

**Comment by GauthamBanasandra** [comment]
My pleasure. :)

**Comment by GauthamBanasandra** [comment]
For some reason, the build failed when I submitted this PR.

**Pull request merged**
