### PR TITLE
Content for Kafka 3.0-BETA

### PR DESCRIPTION
**Pull request by avsej**
@ingenthr @1tylermitchell

### CODE REVIEW

**Comment by amarantha-k** [comment]
@avsej Assuming this PR is yet to be reviewed. Please tag me when it's ready to be merged. Thanks!

**Comment by ingenthr** [comment]
@1tylermitchell said he'd look at this earlier today

**Comment by 1tylermitchell** [comment]
review comments sent and some copy edits done

**Comment by amarantha-k** [comment]
Cherry-picked updates for 4.5. Keeping PR open to merge to master.

**Comment by amarantha-k** [comment]
Merged to master using cherry-pick

**Pull request closed without merging**
