### PR TITLE
Fix invalid option on cbbackupmgr

### PR DESCRIPTION
**Pull request by oxyrox**
replaced --dir with --archive

### CODE REVIEW

**Comment by mattcarabine** [comment]
Looks like you're right @oxyrox - good catch!

Thanks for contributing to the docs, I'll get this merged and backported for you. You should see the change live on the website in a few days.

**Comment by mattcarabine** [comment]
@cb-docs-robot backport to 4.5

**Comment by mattcarabine** [comment]
@cb-docs-robot backport to master

**Comment by oxyrox** [comment]
@mattcarabine Cool, thanks 👍 :)

**Pull request merged**
